# Generated by Django 5.2.7 on 2025-10-22 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gostos_pessoais', models.TextField(blank=True, help_text='Escreva aqui seus gostos e sugestões de presente.', null=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupos.grupo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'grupo')},
            },
        ),
        migrations.AddField(
            model_name='grupo',
            name='participantes',
            field=models.ManyToManyField(related_name='grupos_participando', through='grupos.Participante', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Exclusao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_sorteio', models.CharField(choices=[('amigo', 'Amigo Secreto'), ('inimigo', 'Inimigo Secreto')], max_length=10)),
                ('doador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusoes_feitas', to=settings.AUTH_USER_MODEL)),
                ('excluido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusoes_recebidas', to=settings.AUTH_USER_MODEL)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupos.grupo')),
            ],
            options={
                'verbose_name': 'Exclusão',
                'verbose_name_plural': 'Exclusões',
                'unique_together': {('grupo', 'doador', 'excluido', 'tipo_sorteio')},
            },
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_sorteio', models.CharField(choices=[('amigo', 'Amigo Secreto'), ('inimigo', 'Inimigo Secreto')], max_length=10)),
                ('doador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentes_dados', to=settings.AUTH_USER_MODEL)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupos.grupo')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentes_recebidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('grupo', 'doador', 'tipo_sorteio')},
            },
        ),
    ]
