# Generated by Django 5.2.7 on 2025-10-31 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='genero',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=10, null=True, verbose_name='Gênero'),
        ),
        migrations.AddField(
            model_name='participante',
            name='photo_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='URL da Foto'),
        ),
    ]
