# Generated by Django 5.2.7 on 2025-11-07 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0002_participante_genero_participante_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='participa_amigo',
            field=models.BooleanField(default=True, verbose_name='Participa do Amigo Secreto?'),
        ),
        migrations.AddField(
            model_name='participante',
            name='participa_inimigo',
            field=models.BooleanField(default=True, verbose_name='Participa do Inimigo Secreto?'),
        ),
    ]
