# Generated by Django 5.2.7 on 2025-11-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0003_participante_participa_amigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='genero',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Não Binário', 'Não Binário')], max_length=20, null=True, verbose_name='Gênero'),
        ),
    ]
